version: "3.2"
services:
  caddy:
    image: caddy/caddy
    container_name: caddy-server
    restart: always
    network_mode: "host"
    volumes:
      - ./$CADDYFILE_NAME:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
